import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { Loading } from "./components/Loading";
import { AuthProvider } from "./contexts/AuthProvider";
import { FilterProvider } from "./contexts/FilterContext";
import { FilterListsProvider } from "./contexts/FilterListsContext";
import { FilterTriggerProvider } from "./contexts/FilterTriggerContext";
import { LoadingProvider } from "./contexts/LoagindContext";
import { TypeDeviceProvider } from "./contexts/TypeDevice";
import "./globals.css";
import { isMobileDevice } from "./hooks/useIsMobileDevice";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Diecast",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = await isMobileDevice();

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased min-h-full`}>
        <LoadingProvider>
          <Loading />
          <ToastContainer />
          <TypeDeviceProvider initialIsMobile={isMobile}>
            <AuthProvider>
              <FilterProvider>
                <FilterListsProvider>
                  <FilterTriggerProvider>{children}</FilterTriggerProvider>
                </FilterListsProvider>
              </FilterProvider>
            </AuthProvider>
          </TypeDeviceProvider>
        </LoadingProvider>{" "}
      </body>
    </html>
  );
}
