import { Miniatura } from "./types";

export const minis: Miniatura[] = [
  {
    name: "Ford GT",
    ano: 2022,
    preco: 22.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Chevrolet Camaro SS",
    ano: 2021,
    preco: 21.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Dodge Charger R/T",
    ano: 2020,
    preco: 23.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Nissan GT-R R35",
    ano: 2022,
    preco: 24.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Toyota Supra MK4",
    ano: 2021,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    name: "Lamborghini Huracán",
    ano: 2022,
    preco: 27.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Ferrari F40",
    ano: 2020,
    preco: 26.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Porsche 911 Carrera",
    ano: 2021,
    preco: 24.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "BMW M4",
    ano: 2022,
    preco: 23.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Audi R8",
    ano: 2021,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    name: "McLaren P1",
    ano: 2020,
    preco: 28.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Bugatti Chiron",
    ano: 2022,
    preco: 29.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Koenigsegg Jesko",
    ano: 2023,
    preco: 31.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Pagani Huayra",
    ano: 2021,
    preco: 30.9,
    marca: "Hot Wheels",
  },
  {
    name: "Tesla Model S",
    ano: 2022,
    preco: 22.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Volkswagen Golf GTI",
    ano: 2020,
    preco: 21.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    name: "Mazda RX-7",
    ano: 1999,
    preco: 24.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  { name: "Honda Civic Type R", ano: 2021, preco: 23.9, marca: "Hot Wheels" },
  { name: "Subaru Impreza WRX", ano: 2005, preco: 22.9, marca: "Hot Wheels" },
  {
    name: "Mitsubishi Lancer Evo",
    ano: 2006,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  {
    name: "Chevrolet Corvette C8",
    ano: 2022,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  { name: "Ford Mustang GT", ano: 2021, preco: 23.9, marca: "Hot Wheels" },
  { name: "Dodge Viper GTS", ano: 2019, preco: 25.9, marca: "Hot Wheels" },
  { name: "Jeep Wrangler", ano: 2020, preco: 22.9, marca: "Hot Wheels" },
  {
    name: "Land Rover Defender",
    ano: 2021,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  {
    name: "Chevrolet Silverado",
    ano: 2020,
    preco: 21.9,
    marca: "Hot Wheels",
  },
  { name: "Ford F-150 Raptor", ano: 2022, preco: 26.9, marca: "Hot Wheels" },
  {
    name: "Toyota Land Cruiser",
    ano: 2019,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  { name: "Nissan Skyline R34", ano: 2002, preco: 27.9, marca: "Hot Wheels" },
  { name: "Alfa Romeo Giulia", ano: 2021, preco: 24.9, marca: "Hot Wheels" },
  {
    name: "Mercedes-Benz AMG GT",
    ano: 2022,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  {
    name: "Aston Martin Vantage",
    ano: 2021,
    preco: 28.9,
    marca: "Hot Wheels",
  },
  {
    name: "Bentley Continental GT",
    ano: 2020,
    preco: 29.9,
    marca: "Hot Wheels",
  },
  { name: "Jaguar F-Type", ano: 2021, preco: 26.9, marca: "Hot Wheels" },
  { name: "Peugeot 208 GT", ano: 2022, preco: 21.9, marca: "Hot Wheels" },
  { name: "Renault Megane RS", ano: 2020, preco: 22.9, marca: "Hot Wheels" },
  { name: "Fiat 500 Abarth", ano: 2019, preco: 20.9, marca: "Hot Wheels" },
  { name: "Mini Cooper S", ano: 2021, preco: 22.9, marca: "Hot Wheels" },
  { name: "Cadillac CTS-V", ano: 2020, preco: 25.9, marca: "Hot Wheels" },
  { name: "Chevrolet Impala", ano: 1967, preco: 24.9, marca: "Hot Wheels" },
  { name: "Toyota Corolla GR", ano: 2023, preco: 26.9, marca: "Hot Wheels" },
  { name: "Honda NSX", ano: 2022, preco: 28.9, marca: "Hot Wheels" },
  { name: "Ford Bronco", ano: 2021, preco: 24.9, marca: "Hot Wheels" },
  { name: "Chevrolet Blazer", ano: 2020, preco: 22.9, marca: "Hot Wheels" },
  { name: "BMW M3 E46", ano: 2003, preco: 27.9, marca: "Hot Wheels" },
  { name: "Audi RS6 Avant", ano: 2022, preco: 29.9, marca: "Hot Wheels" },
  {
    name: "Mercedes-Benz G63 AMG",
    ano: 2021,
    preco: 30.9,
    marca: "Hot Wheels",
  },
  {
    name: "Porsche Taycan Turbo",
    ano: 2022,
    preco: 28.9,
    marca: "Hot Wheels",
  },
  { name: "Tesla Model 3", ano: 2021, preco: 22.9, marca: "Hot Wheels" },
  { name: "Volkswagen Kombi", ano: 1975, preco: 23.9, marca: "Hot Wheels" },
  {
    name: "Chevrolet Chevelle SS",
    ano: 1970,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  { name: "Ford Maverick", ano: 1974, preco: 25.9, marca: "Hot Wheels" },
  {
    name: "Dodge Challenger SRT",
    ano: 2022,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  { name: "Pontiac GTO", ano: 1969, preco: 26.9, marca: "Hot Wheels" },
  { name: "Shelby Cobra 427", ano: 1965, preco: 29.9, marca: "Hot Wheels" },
  {
    name: "Lamborghini Aventador",
    ano: 2021,
    preco: 31.9,
    marca: "Hot Wheels",
  },
  { name: "Ferrari LaFerrari", ano: 2020, preco: 32.9, marca: "Hot Wheels" },
  { name: "Pagani Zonda R", ano: 2019, preco: 33.9, marca: "Hot Wheels" },
  { name: "Bugatti Veyron", ano: 2018, preco: 30.9, marca: "Hot Wheels" },
  {
    name: "Koenigsegg Agera RS",
    ano: 2019,
    preco: 34.9,
    marca: "Hot Wheels",
  },
  { name: "Nissan 370Z", ano: 2020, preco: 23.9, marca: "Hot Wheels" },
  { name: "Toyota AE86 Trueno", ano: 1986, preco: 26.9, marca: "Hot Wheels" },
  { name: "Mazda MX-5 Miata", ano: 2021, preco: 22.9, marca: "Hot Wheels" },
  { name: "Honda S2000", ano: 2004, preco: 25.9, marca: "Hot Wheels" },
  { name: "Subaru BRZ", ano: 2022, preco: 24.9, marca: "Hot Wheels" },
  { name: "Toyota GR86", ano: 2023, preco: 25.9, marca: "Hot Wheels" },
  { name: "Chevrolet Nova SS", ano: 1972, preco: 26.9, marca: "Hot Wheels" },
  {
    name: "Ford Escort RS Cosworth",
    ano: 1994,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  { name: "Audi Quattro", ano: 1985, preco: 28.9, marca: "Hot Wheels" },
  { name: "BMW i8", ano: 2020, preco: 26.9, marca: "Hot Wheels" },
  { name: "Mercedes-Benz SLK", ano: 2019, preco: 23.9, marca: "Hot Wheels" },
  { name: "Volvo XC90", ano: 2021, preco: 24.9, marca: "Hot Wheels" },
  { name: "Chevrolet Tahoe", ano: 2020, preco: 25.9, marca: "Hot Wheels" },
  { name: "Ford Explorer", ano: 2021, preco: 24.9, marca: "Hot Wheels" },
  { name: "RAM 1500 TRX", ano: 2022, preco: 29.9, marca: "Hot Wheels" },
  { name: "GMC Hummer EV", ano: 2023, preco: 32.9, marca: "Hot Wheels" },
  { name: "Jeep Gladiator", ano: 2021, preco: 26.9, marca: "Hot Wheels" },
  { name: "Suzuki Jimny", ano: 2022, preco: 23.9, marca: "Hot Wheels" },
  {
    name: "Land Rover Range Rover Sport",
    ano: 2021,
    preco: 28.9,
    marca: "Hot Wheels",
  },
  { name: "Porsche Cayman GT4", ano: 2022, preco: 29.9, marca: "Hot Wheels" },
];
