import { toast } from "react-toastify";
import { Miniatura, PaginationInfo } from "./types";

export const formatImage = (img?: string) => {
  if (!img) return undefined;

  return img.startsWith("data:") ? img : `data:image/jpeg;base64,${img}`;
};

export const PaginationDefault: PaginationInfo = {
  pageNumber: 0,
  pageNumberInitial: 0,
  totalPages: 0,
  totalElements: 0,
  elementsPerPage: 4,
};

export const minis: Miniatura[] = [
  {
    id: 1,
    name: "Ford GT",
    ano: 2022,
    preco: 22.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 2,
    name: "Chevrolet Camaro SS",
    ano: 2021,
    preco: 21.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 3,
    name: "Dodge Charger R/T",
    ano: 2020,
    preco: 23.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 4,
    name: "Nissan GT-R R35",
    ano: 2022,
    preco: 24.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 5,
    name: "Toyota Supra MK4",
    ano: 2021,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    id: 6,
    name: "Lamborghini Huracán",
    ano: 2022,
    preco: 27.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 7,
    name: "Ferrari F40",
    ano: 2020,
    preco: 26.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 8,
    name: "Porsche 911 Carrera",
    ano: 2021,
    preco: 24.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 9,
    name: "BMW M4",
    ano: 2022,
    preco: 23.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  { id: 10, name: "Audi R8", ano: 2021, preco: 25.9, marca: "Hot Wheels" },
  {
    id: 11,
    name: "McLaren P1",
    ano: 2020,
    preco: 28.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 12,
    name: "Bugatti Chiron",
    ano: 2022,
    preco: 29.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 13,
    name: "Koenigsegg Jesko",
    ano: 2023,
    preco: 31.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 14,
    name: "Pagani Huayra",
    ano: 2021,
    preco: 30.9,
    marca: "Hot Wheels",
  },
  {
    id: 15,
    name: "Tesla Model S",
    ano: 2022,
    preco: 22.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 16,
    name: "Volkswagen Golf GTI",
    ano: 2020,
    preco: 21.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 17,
    name: "Mazda RX-7",
    ano: 1999,
    preco: 24.9,
    marca: "Hot Wheels",
    image: "/image/car.jpeg",
  },
  {
    id: 18,
    name: "Honda Civic Type R",
    ano: 2021,
    preco: 23.9,
    marca: "Hot Wheels",
  },
  {
    id: 19,
    name: "Subaru Impreza WRX",
    ano: 2005,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  {
    id: 20,
    name: "Mitsubishi Lancer Evo",
    ano: 2006,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  {
    id: 21,
    name: "Chevrolet Corvette C8",
    ano: 2022,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  {
    id: 22,
    name: "Ford Mustang GT",
    ano: 2021,
    preco: 23.9,
    marca: "Hot Wheels",
  },
  {
    id: 23,
    name: "Dodge Viper GTS",
    ano: 2019,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    id: 24,
    name: "Jeep Wrangler",
    ano: 2020,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  {
    id: 25,
    name: "Land Rover Defender",
    ano: 2021,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  {
    id: 26,
    name: "Chevrolet Silverado",
    ano: 2020,
    preco: 21.9,
    marca: "Hot Wheels",
  },
  {
    id: 27,
    name: "Ford F-150 Raptor",
    ano: 2022,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  {
    id: 28,
    name: "Toyota Land Cruiser",
    ano: 2019,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    id: 29,
    name: "Nissan Skyline R34",
    ano: 2002,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  {
    id: 30,
    name: "Alfa Romeo Giulia",
    ano: 2021,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  {
    id: 31,
    name: "Mercedes-Benz AMG GT",
    ano: 2022,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  {
    id: 32,
    name: "Aston Martin Vantage",
    ano: 2021,
    preco: 28.9,
    marca: "Hot Wheels",
  },
  {
    id: 33,
    name: "Bentley Continental GT",
    ano: 2020,
    preco: 29.9,
    marca: "Hot Wheels",
  },
  {
    id: 34,
    name: "Jaguar F-Type",
    ano: 2021,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  {
    id: 35,
    name: "Peugeot 208 GT",
    ano: 2022,
    preco: 21.9,
    marca: "Hot Wheels",
  },
  {
    id: 36,
    name: "Renault Megane RS",
    ano: 2020,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  {
    id: 37,
    name: "Fiat 500 Abarth",
    ano: 2019,
    preco: 20.9,
    marca: "Hot Wheels",
  },
  {
    id: 38,
    name: "Mini Cooper S",
    ano: 2021,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  {
    id: 39,
    name: "Cadillac CTS-V",
    ano: 2020,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    id: 40,
    name: "Chevrolet Impala",
    ano: 1967,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  {
    id: 41,
    name: "Toyota Corolla GR",
    ano: 2023,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  { id: 42, name: "Honda NSX", ano: 2022, preco: 28.9, marca: "Hot Wheels" },
  { id: 43, name: "Ford Bronco", ano: 2021, preco: 24.9, marca: "Hot Wheels" },
  {
    id: 44,
    name: "Chevrolet Blazer",
    ano: 2020,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  { id: 45, name: "BMW M3 E46", ano: 2003, preco: 27.9, marca: "Hot Wheels" },
  {
    id: 46,
    name: "Audi RS6 Avant",
    ano: 2022,
    preco: 29.9,
    marca: "Hot Wheels",
  },
  {
    id: 47,
    name: "Mercedes-Benz G63 AMG",
    ano: 2021,
    preco: 30.9,
    marca: "Hot Wheels",
  },
  {
    id: 48,
    name: "Porsche Taycan Turbo",
    ano: 2022,
    preco: 28.9,
    marca: "Hot Wheels",
  },
  {
    id: 49,
    name: "Tesla Model 3",
    ano: 2021,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  {
    id: 50,
    name: "Volkswagen Kombi",
    ano: 1975,
    preco: 23.9,
    marca: "Hot Wheels",
  },
  {
    id: 51,
    name: "Chevrolet Chevelle SS",
    ano: 1970,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  {
    id: 52,
    name: "Ford Maverick",
    ano: 1974,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    id: 53,
    name: "Dodge Challenger SRT",
    ano: 2022,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  { id: 54, name: "Pontiac GTO", ano: 1969, preco: 26.9, marca: "Hot Wheels" },
  {
    id: 55,
    name: "Shelby Cobra 427",
    ano: 1965,
    preco: 29.9,
    marca: "Hot Wheels",
  },
  {
    id: 56,
    name: "Lamborghini Aventador",
    ano: 2021,
    preco: 31.9,
    marca: "Hot Wheels",
  },
  {
    id: 57,
    name: "Ferrari LaFerrari",
    ano: 2020,
    preco: 32.9,
    marca: "Hot Wheels",
  },
  {
    id: 58,
    name: "Pagani Zonda R",
    ano: 2019,
    preco: 33.9,
    marca: "Hot Wheels",
  },
  {
    id: 59,
    name: "Bugatti Veyron",
    ano: 2018,
    preco: 30.9,
    marca: "Hot Wheels",
  },
  {
    id: 60,
    name: "Koenigsegg Agera RS",
    ano: 2019,
    preco: 34.9,
    marca: "Hot Wheels",
  },
  { id: 61, name: "Nissan 370Z", ano: 2020, preco: 23.9, marca: "Hot Wheels" },
  {
    id: 62,
    name: "Toyota AE86 Trueno",
    ano: 1986,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  {
    id: 63,
    name: "Mazda MX-5 Miata",
    ano: 2021,
    preco: 22.9,
    marca: "Hot Wheels",
  },
  { id: 64, name: "Honda S2000", ano: 2004, preco: 25.9, marca: "Hot Wheels" },
  { id: 65, name: "Subaru BRZ", ano: 2022, preco: 24.9, marca: "Hot Wheels" },
  { id: 66, name: "Toyota GR86", ano: 2023, preco: 25.9, marca: "Hot Wheels" },
  {
    id: 67,
    name: "Chevrolet Nova SS",
    ano: 1972,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  {
    id: 68,
    name: "Ford Escort RS Cosworth",
    ano: 1994,
    preco: 27.9,
    marca: "Hot Wheels",
  },
  { id: 69, name: "Audi Quattro", ano: 1985, preco: 28.9, marca: "Hot Wheels" },
  { id: 70, name: "BMW i8", ano: 2020, preco: 26.9, marca: "Hot Wheels" },
  {
    id: 71,
    name: "Mercedes-Benz SLK",
    ano: 2019,
    preco: 23.9,
    marca: "Hot Wheels",
  },
  { id: 72, name: "Volvo XC90", ano: 2021, preco: 24.9, marca: "Hot Wheels" },
  {
    id: 73,
    name: "Chevrolet Tahoe",
    ano: 2020,
    preco: 25.9,
    marca: "Hot Wheels",
  },
  {
    id: 74,
    name: "Ford Explorer",
    ano: 2021,
    preco: 24.9,
    marca: "Hot Wheels",
  },
  { id: 75, name: "RAM 1500 TRX", ano: 2022, preco: 29.9, marca: "Hot Wheels" },
  {
    id: 76,
    name: "GMC Hummer EV",
    ano: 2023,
    preco: 32.9,
    marca: "Hot Wheels",
  },
  {
    id: 77,
    name: "Jeep Gladiator",
    ano: 2021,
    preco: 26.9,
    marca: "Hot Wheels",
  },
  { id: 78, name: "Suzuki Jimny", ano: 2022, preco: 23.9, marca: "Hot Wheels" },
  {
    id: 79,
    name: "Land Rover Range Rover Sport",
    ano: 2021,
    preco: 28.9,
    marca: "Hot Wheels",
  },
  {
    id: 80,
    name: "Porsche Cayman GT4",
    ano: 2022,
    preco: 29.9,
    marca: "Hot Wheels",
  },
];

export const handleRedirectToWhatsApp = (
  mini: Miniatura,
  link: string,
  isMobile: boolean,
) => {
  const number = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER;

  // tirar quando o icone de whatsapp só tiver para cliente
  // handleVisibleFormMini();
  //
  const message = `Olá, tenho interesse na miniatura ${mini.nome} ${mini.ano}, da ${mini.marca} - ${link}`;
  const encodedMessage = encodeURIComponent(message);

  // if (isMobile) {
  //   const url = `https://api.whatsapp.com/send?phone=${number}&text=${encodedMessage}`;
  //   window.location.href = url;
  // } else {
  window.open(`https://wa.me/${number}?text=${encodedMessage}`, "_blank");
  // }
};

export const handleDownloadCatalog = () => {
  toast.success("Download do catálogo iniciado 🚀");
};
